kind: Service
apiVersion: v1
metadata:
  name: myapp-svc
  namespace: mylocal
  labels:
    app: myapp  
spec:
  type: NodePort
  ports:
    - port: 3000
      nodePort: 30201
  selector:
    app: myapp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  namespace: mylocal
  labels:
    app: myapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp
          image: docker.io/ankitrkharb/nodejsfirst:1.0
          ports:
            - containerPort: 3000